" general
syntax on
filetype off

set encoding=utf-8
set t_Co=256
set nocompatible
set laststatus=2
set background=light
set number
set hlsearch
set splitright
set splitbelow
set ttimeoutlen=0

" display whitespace
set list
set listchars=tab:▸\ ,trail:·,nbsp:·

" show 80 column line
set colorcolumn=80

" Highlight characters in lines longer than 80 chars
match ErrorMsg '\%>80v.\+'

" indentation
set autoindent
set noexpandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

" cd folder preview
set wildmenu
set wildmode=list:longest

" no swap files
set noswapfile
set nobackup
set nowritebackup

let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
set wildignore+=*/tmp/*,*.scssc,*.sassc,*.class,*.DS_Store
set wildignore+=*/vendor/bundle/*,*/server/*,*/public/*
set wildignore+=*theaterjobs*/vendor/*,*/web/bundles/*,*/app/cache/*,*/vendor/bundles*

" allow hiding modified buffers
set hidden

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set backspace=indent,eol,start

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'mileszs/ack.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
" Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'sickill/vim-monokai'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'godlygeek/tabular'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'adimit/prolog.vim'

call vundle#end()            " required
filetype plugin indent on    " required

" colorscheme Tomorrow-Night-Eighties
colorscheme monokai

" Configure airline
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline#extensions#hunks#enabled = 0
let g:airline#extensions#whitespace#enabled = 0

" Mappings
"map :nt :NERDTree
imap kj <esc>
nmap <C-b> :CtrlPBuffer<cr>

nnoremap <C-J> mao<Esc>`a
nnoremap <C-K> maO<Esc>`a

" Highlight colors for gitgutter
highlight clear SignColumn
highlight GitGutterAdd ctermfg=2 ctermbg=235 guifg=#009900 guibg=Grey"
highlight GitGutterChange ctermfg=3 ctermbg=235 guifg=#bbbb00 guibg=Grey
highlight GitGutterDelete ctermfg=1 ctermbg=235 guifg=#ff2222 guibg=Grey
highlight link GitGutterChangeDelete GitGutterChange

highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

