#!/bin/zsh
# aliases

# muscle memory
alias open='xdg-open'
alias o='open'

#fd without ignore files by default
alias fd='fdfind --no-ignore-vcs --hidden'
alias fdig="fd -ig"

#rnr always in action mode and no dumps
alias rn='rnr -f --no-dump'
alias rn-file='rnr -f --no-dump'
alias rn-dir='rnr -D -f --no-dump'

#navigation
alias b='cd ..'
alias bp='cd -'

#git
alias g='git'

# make
alias m='make'

#python
alias p='python3'
alias pp='p -m pip'

# open files
alias o='open'

# nicer ls
alias ls > /dev/null && unalias ls
alias ls='ls -G --color=auto'
alias ll='ls -lh -F'
alias lav='ls -lAh -F'
alias lavs='ls -lSAh -F'
alias lavt='ls -lAh -F -t'
alias la='ls -1hs -F'
# confirm before overwriting something
alias cp="cp -viRp"
# human-readable sizes
alias df='df -h'
# measuring
alias dusch='du -sch'
# show sizes in MB
alias free='free -m'
# remove stuff recursivly
alias rr='rm -r'

# grepping with color
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# equal rights !!! xD
alias woman='man'

#
alias butt='$HOME/Library/Application\ Support/itch/apps/butler/butler'
