#!/bin/bash

if [ ! -e $HOME/.Xresources ]; then
	ln -s $WS_CFG_PATH/dotfiles/Xresources $HOME/.Xresources
fi

if [ ! -e $HOME/.bash_logout ]; then
	ln -s $WS_CFG_PATH/dotfiles/bash_logout $HOME/.bash_logout
fi

if [ ! -e $HOME/.bashrc ]; then
	ln -s $WS_CFG_PATH/dotfiles/bashrc $HOME/.bashrc
fi

if [ ! -e $HOME/.dmrc ]; then
	ln -s $WS_CFG_PATH/dotfiles/dmrc $HOME/.dmrc
fi

if [ ! -e $HOME/.gitconfig ]; then
	# setup live copy
	cp -Rav "$WS_CFG_PATH/dotfiles/gitconfig" "$WS_CFG_PATH/live/gitconfig"
	# query git default user
local setup_default_user_code=$(cat << EOF
import sys, configparser
config = configparser.ConfigParser()
config.read(sys.argv[1])
user = { 
	'name':  input('Default git user name: '), 
	'email': input('Default git email:     ')
}
config['user'] = user
with open(sys.argv[1], 'w') as f:
	config.write(f)
EOF
)
	python3 -c "$setup_default_user_code" "$WS_CFG_PATH/live/gitconfig"
	# append to config file and write to home
	ln -s $WS_CFG_PATH/live/gitconfig $HOME/.gitconfig
fi

if [ ! -e $HOME/.profile ]; then
	ln -s $WS_CFG_PATH/dotfiles/profile $HOME/.profile
fi

if [ ! -e $HOME/.zshrc ]; then
	ln -s $WS_CFG_PATH/dotfiles/zshrc $HOME/.zshrc
fi

if [ ! -e $HOME/.vimrc ]; then
	ln -s $WS_CFG_PATH/dotfiles/vimrc $HOME/.vimrc
fi
