#!/bin/bash

if [ ! -e $HOME/.bash_logout ]; then
	ln -s $CONFIGURATION_PATH/dotfiles/bash_logout $HOME/.bash_logout
fi

if [ ! -e $HOME/.gitconfig ]; then
	ln -s $CONFIGURATION_PATH/dotfiles/gitconfig $HOME/.gitconfig
fi

if [ ! -e $HOME/.bashrc ]; then
	ln -s $CONFIGURATION_PATH/dotfiles/bashrc $HOME/.bashrc
fi