#!/bin/bash

# entry point

# change this to your liking
export CONFIGURATION_PATH="$HOME/Workspace/Config"

# set guard
export CONFIGURATION_LOADED=yes

# define function to reinitialize
workspace_config_load () {
	# setup dotfiles
	source "$CONFIGURATION_PATH/link-dotfiles"

	# setup options
	source "$CONFIGURATION_PATH/options"

	# setup aliases
	source "$CONFIGURATION_PATH/aliases"

	# setup exports
	source "$CONFIGURATION_PATH/exports"

	# setup helper functions
	source "$CONFIGURATION_PATH/functions"

	# import additional functionality
	source "$CONFIGURATION_PATH/imports"

	# setup custom keyboard layout
	source "$CONFIGURATION_PATH/keyboard-layout"

}

# and call it
workspace_config_load
