#!/bin/bash

# entry point

# change this to your liking
export CONFIGURATION_PATH="/d/Workspace/Config"

# set guard
export CONFIGURATION_LOADED=yes

workspace_config_plugin () {
	if ((1 != $#)); then
		echo "no plugin name provided"
		return 1
	fi

	(cd "$CONFIGURATION_PATH/plugins/$1" && ./run)
	return 0
}

# define function to reinitialize
workspace_config_load () {
	# setup dotfiles
	source "$CONFIGURATION_PATH/link-dotfiles"

	# setup options
	source "$CONFIGURATION_PATH/options"

	# setup aliases
	source "$CONFIGURATION_PATH/aliases"

	# setup exports
	source "$CONFIGURATION_PATH/exports"

	# setup helper functions
	source "$CONFIGURATION_PATH/functions"

	# import additional functionality
	source "$CONFIGURATION_PATH/imports"
}

# and call it
workspace_config_load
